### ISSUE TITLE
Compatibility with logstash 2.1?

### ISSUE THREAD

**Issue by ebuildy** [logstash-plugins/logstash-output-webhdfs#12]
It seems the latest version available at https://rubygems.org/gems/logstash-output-hdfs requires

```
logstash-core < 2.0.0, >= 1.4.0
```

Hence, trying install this plugin with logstash 2.1 gives:

```
Bundler could not find compatible versions for gem "logstash":
  In Gemfile:
    logstash-output-hdfs (>= 0) java depends on
      logstash (< 2.0.0, >= 1.4.0) java
Could not find gem 'logstash (< 2.0.0, >= 1.4.0) java', which is required by gem 'logstash-output-hdfs (>= 0) java', in any of the sources.
```

Manualy installation works fine:

```
cd /tmp && \
    git clone https://github.com/logstash-plugins/logstash-output-webhdfs.git && \
    cd logstash-output-webhdfs && \
    gem build logstash-output-webhdfs.gemspec && \
    /opt/logstash/bin/plugin install /tmp/logstash-output-webhdfs/logstash-output-webhdfs-2.0.2.gem
```

**Comment by dstore-dbap** [comment]
Hi ebuildy,
thanks for your feedback, will have a look at it. Will post an update here as soon as this is fixed.
Take care,
Björn

**Comment by dstore-dbap** [comment]
I think you ended up at the wrong plugin. You are referring to logstash-output-hdfs but this plugin here is using webhdfs to store data in hdfs. The hdfs plugin is not maintained here so please file your issue @https://github.com/avishai-ish-shalom/logstash-hdfs.
Take care,
Björn

**Comment by ebuildy** [comment]
Like my hero says "D'oh" 

Sorry for the trouble, thanks for the help, it's working like a charm btw.

**Comment by dstore-dbap** [comment]
Glad to hear that its working for you now ;)

Take care and have a nice weekend,
Björn
