### ISSUE TITLE
Idea/enhancement: support for HA namenodes

### ISSUE THREAD

**Issue by Alex-Ikanow** [logstash-plugins/logstash-output-webhdfs#17]
You could make a strong case that this could/should either be implemented in the underlying webhdfs module or not at all

With HDP2.3 at least, HA HDFS is now enabled by default. There are 2 namenodes (active and standby) and they can switch states whenever they please.

If you hit the wrong one via WebHDFS you (are guaranteed to) get the following error (in a 403):

`{\"RemoteException\":{\"exception\":\"StandbyException\",\"javaClassName\":\"org.apache.hadoop.ipc.StandbyException\",\"message\":\"Operation category READ is not supported in state standby\"}})", :level=>:error, :file=>"logstash/outputs/webhdfs.rb", :line=>"129", :method=>"register"}`

So you could be a hero and accept 2 namenodes as configuration and then just switch between them (at most once per record!) whenever you get the above error..

(Incidentally the alternative is apparently to use HttpFS ... I see that the webhdfs library you use has "experimental" HttpFS support - do you expose that?)

**Comment by dstore-dbap** [comment]
Hi Alex,

thanks for the heads up here! 
Will have a look at it, as soon as I find the time. Sadly, that might be only as early as next week as I'm quite busy at the moment. Will keep you posted...

Take care and all the best,
Björn

**Comment by dstore-dbap** [comment]
Hi Alex,
sorry for getting back to you took me so long. Had quite a busy week. 
As to your question concerning httpfs support: you can enable it by setting the config parameter 'use_httpfs' to true in the logstash config of this module.

I will have a look at your suggested enhancement today.
Take care,
Björn

**Comment by dstore-dbap** [comment]
Hi Alex,
just pushed a new version that supports failover to the ha_namenodes branch. 
Two new config parameters can now be used in the logstash configuration of this module:
standby_host, the standby namenode.
standby_port, defaults to 50070.

Maybe you could give this a try with your setup and let me know how this works for you?

Take care and all the best,
Björn

**Comment by Alex-Ikanow** [comment]
Awesome thanks! I'll give it a whirl

**Comment by cburch** [comment]
Hey Björn,

I work with Alex and ended up testing the changes you made, they worked like a charm thanks!  Switched over just fine when I brought down the NN and continued to write to the standby.

I'm not sure if Apache has plans in the future to change the spec to allow more standby nodes for failover but you might want to consider making the hosts param an array of host:port strings to future proof it in case they decide to allow 2+ standby nodes, otherwise it works just fine right now!  (I doubt they'll change it anytime soon).

Thanks for the quick updates!
Caleb

**Comment by dstore-dbap** [comment]
Hi Caleb,

thanks for testing this with your setup and for your feedback. Glad to hear that it is also working for you.
Using an array with host:port items as configuration parameter is a good idea. I just don't want to break already existing configurations. 
Still, I'm going to give it some more thought. I think sooner or later there will be the possibility of multiple standby nodes.

As soon as I decided on a solution and merge this to master I will post an update here. 

Thanks again and take care,
Björn

**Comment by dstore-dbap** [comment]
Hi again,
merged this just now into master with commit https://github.com/logstash-plugins/logstash-output-webhdfs/commit/98838d5908b37e3721683300cd224b267f909a78.

As to not breaking existing configurations and to avoid premature optimization the original host and port configuration parameters were not replaced by a dict of host:port combinations to allow for more than two failover hosts. If in future this will be supported by webhdfs we might need to change this.

Thanks again for your feedback and help in resolving this ;)
Will close this issue now. 

Take care and all the best,
Björn
