### ISSUE TITLE
WebHDFS:IOError

### ISSUE THREAD

**Issue by famasya** [logstash-plugins/logstash-output-webhdfs#24]
Hi, i encounter an error while trying to save logstash into HDFS. The debug looked like this:

`Failed to flush outgoing items {:outgoing_count=>93, :exception=>"WebHDFS::IOError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/webhdfs-0.8.0/lib/webhdfs/client_v1.rb:401:in`request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/webhdfs-0.8.0/lib/webhdfs/client_v1.rb:270:in `operate_requests'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/webhdfs-0.8.0/lib/webhdfs/client_v1.rb:73:in`create'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-webhdfs-3.0.2/lib/logstash/outputs/webhdfs.rb:211:in `write_data'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-webhdfs-3.0.2/lib/logstash/outputs/webhdfs.rb:195:in`flush'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-webhdfs-3.0.2/lib/logstash/outputs/webhdfs.rb:183:in`flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in`each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:193:in`buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1479:in`loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}`

And it was repeated. My configurations are

```
input {
  redis {
    data_type => "list"
    key => "filebeat"
  }
}

filter {
  if [type] == "conn_log" {
    csv {
      columns => ["ts","uid","id.orig_h","id.orig_p","id.resp_h","id.resp_p","proto","service","duration","orig_bytes","resp_bytes","conn_state","local_orig","local_resp","missed_bytes","history","orig_pkts","orig_ip_bytes","resp_pkts","resp_ip_bytes","tunnel_parents"]
      separator => "    "
    }
  } else if [type] == "weird_log" {
    csv {
      columns => ["ts","uid","id.orig_h","id.orig_p","id.resp_h","id.resp_p","name","addl","notice","peer"]
      separator => "    "
    }
  } else {
    csv {
      columns => ["ts","uid","id.orig_h","id.orig_p","id.resp_h","id.resp_p","fuid","file_mime_type","file_desc","proto","note","msg","sub","src","dst","p","n","peer_descr","actions","suppress_for","dropped","remote_location.country_code","remote_location.region","remote_location.city","remote_location.latitude","remote_location.longitude"]
      separator => "    "
    }
  }
}

output {
  stdout {
    codec => rubydebug
  }
  webhdfs {
    host => "127.0.0.1"
    path => "/user/logstash/dt=%{+YYYY-MM-dd}/%{@source_host}-%{+HH}.log"
    user => "hduser"
  }
  file {
    path => "logs/redis-%{+YYYY-MM-dd}.txt"
  }
}
```

I use latest (2.4) version of logstash

**Comment by dstore-dbap** [comment]
Hi famasya!
Thanks for opening this issue. Will have a look at the problem in the next couple of days. As soon as I have some news, I will update this issue. 

Take care and all the best,
Björn

**Comment by dstore-dbap** [comment]
Hi famasya,

the error message you posted suggests that there was some kind of problem with your webhdfs backend (WebHDFS::IOError).

Could you please check, if the backend is running and ok?

**Comment by famasya** [comment]
Yes I checked it and eventually it works after I did some system tuning. I think it's solved for now.

**Comment by chengwei-li** [comment]
Recently, I have come across the problem you have, can you tell me how did you solve it? What is the direction of tuning? thank you very much!

**Comment by reilee** [comment]
@famasya could you please share how did you fix it.

**Comment by ciurlaro** [comment]
> Yes I checked it and eventually it works after I did some system tuning. I think it's solved for now.

It is good practice to share the solution for problems you asked help for.
