### ISSUE TITLE
Failed to flush outgoing items {:outgoing_count=>1, :exception=>"WebHDFS::ServerError"

### ISSUE THREAD

**Issue by jacklu2016** [logstash-plugins/logstash-output-webhdfs#28]
The full error log is
`Failed to flush outgoing items {:outgoing_count=>1, :exception=>"WebHDFS::ServerError", :backtrace=>["/home/logstash/logstash-5.0.1/vendor/bundle/jruby/1.9/gems/webhdfs-0.8.0/lib/webhdfs/client_v1.rb:351:in `request'", "/home/logstash/logstash-5.0.1/vendor/bundle/jruby/1.9/gems/webhdfs-0.8.0/lib/webhdfs/client_v1.rb:349:in `request'", "/home/logstash/logstash-5.0.1/vendor/bundle/jruby/1.9/gems/webhdfs-0.8.0/lib/webhdfs/client_v1.rb:270:in `operate_requests'", "/home/logstash/logstash-5.0.1/vendor/bundle/jruby/1.9/gems/webhdfs-0.8.0/lib/webhdfs/client_v1.rb:73:in `create'", "/home/logstash/logstash-5.0.1/vendor/bundle/jruby/1.9/gems/logstash-output-webhdfs-3.0.2/lib/logstash/outputs/webhdfs.rb:211:in `write_data'", "/home/logstash/logstash-5.0.1/vendor/bundle/jruby/1.9/gems/logstash-output-webhdfs-3.0.2/lib/logstash/outputs/webhdfs.rb:195:in `flush'", "org/jruby/RubyHash.java:1342:in `each'", "/home/logstash/logstash-5.0.1/vendor/bundle/jruby/1.9/gems/logstash-output-webhdfs-3.0.2/lib/logstash/outputs/webhdfs.rb:183:in `flush'", "/home/logstash/logstash-5.0.1/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/home/logstash/logstash-5.0.1/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'", "/home/logstash/logstash-5.0.1/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:159:in `buffer_receive'", "/home/logstash/logstash-5.0.1/vendor/bundle/jruby/1.9/gems/logstash-output-webhdfs-3.0.2/lib/logstash/outputs/webhdfs.rb:166:in `receive'", "/home/logstash/logstash-5.0.1/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "org/jruby/RubyArray.java:1613:in `each'", "/home/logstash/logstash-5.0.1/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "/home/logstash/logstash-5.0.1/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:19:in `multi_receive'", "/home/logstash/logstash-5.0.1/logstash-core/lib/logstash/output_delegator.rb:42:in `multi_receive'", "/home/logstash/logstash-5.0.1/logstash-core/lib/logstash/pipeline.rb:297:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/home/logstash/logstash-5.0.1/logstash-core/lib/logstash/pipeline.rb:296:in `output_batch'", "/home/logstash/logstash-5.0.1/logstash-core/lib/logstash/pipeline.rb:252:in `worker_loop'", "/home/logstash/logstash-5.0.1/logstash-core/lib/logstash/pipeline.rb:225:in `start_workers'"]}`

- logstash Version: 5.0.1
- Operating System: Red hat 6.5
- Config File 
output {
   #stdout { codec => rubydebug }
  webhdfs {
    host => "**.**.**.**"
    port => "50070"
    path => "/user/logstash/dt=%{+YYYY-MM-dd}/logs-%{+HH}.log"
    user => "www"
  }
}
www is the hadoop mangent user

**Comment by jordansissel** [comment]
I don't know much about webhdfs, but looking at the error message, it looks like this happens when the webhdfs output is attempting to create a new file in HDFS (outputs/webhdfs.rb:211) and this operation fails somehow. The start of the stack trace is within the `webhdfs` ruby library. 

The first line of the stack trace refers to this line of code: https://github.com/kzk/webhdfs/blob/v0.8.0/lib/webhdfs/client_v1.rb#L351

>  raise WebHDFS::ServerError, "Failed to connect to host #{host}:#{port}, #{e.message}"

If I had to guess, it sounds like the webhdfs output was unable to connect somehow.

**Comment by dstore-dbap** [comment]
As Jordan has already pointed out, this error message points to a communication OR access right problem. Please make sure, that the webhdfs user has sufficient access rights in the configured output directory to create and append to files.

**Comment by dstore-dbap** [comment]
@jacklu2016 Do you have any news concerning your issue? Was jordans or my post in any way helpful to narrow down the problem? If it still persists, please let us know - otherwise I'm going to close this issue next week.

Take care and all the best,
Björn

**Comment by dstore-dbap** [comment]
Hi jacklu2016,

since we did not hear from you again, I do hope the issue got solved. I'm closing it now. If it does still persist, please open up a new ticket.

Take care and have a nice christmas!
Björn
