### ISSUE TITLE
feature request: support for kerberos via keytab

### ISSUE THREAD

**Issue by iolo** [logstash-plugins/logstash-output-webhdfs#29]
underlying webhdfs module already support it.
please, make it configurable:

```ruby
client.kerberos = true
client.kerberos_keytab = "/path/to/your/keytab/file"
```

**Comment by dstore-dbap** [comment]
Hi iolo,

I just merged the kerberos branch to master. New configuration parameters are:
use_kerberos_auth
kerberos_keytab

Please let me know if you encounter any issues.

Take care,
Björn

**Comment by indijanc** [comment]
Will this also work with the webhdfs listening on https? I guess this is a separate enhancement.

P.S: Never mind, I see ssl support in the same commit.

**Comment by dstore-dbap** [comment]
Hopefully the merge solved your issues. I will close this case tomorrow, if you don't have any other problems.

Take care,
Björn

**Comment by iolo** [comment]
it works!
thanks @dstore-dbap

**Comment by dstore-dbap** [comment]
Hi iolo,
glad to hear that ;) I will close this issue then.

Take care and all the best,
Björn

**Comment by redbaron4** [comment]
Hi @iolo Sorry for spamming this thread but could you get the keytab to work _without_ doing a `kinit` first? In my case just specifying the keytab file causes a "No credentials found" error but if I do a `kinit -kt mykeytab` everything works (even if I don't specify keytab in output)

**Comment by yj7778826** [comment]
> 
> 
> Hi @iolo Sorry for spamming this thread but could you get the keytab to work _without_ doing a `kinit` first? In my case just specifying the keytab file causes a "No credentials found" error but if I do a `kinit -kt mykeytab` everything works (even if I don't specify keytab in output)

I have same problem on logstash 6.3.2
