### ISSUE TITLE
Incorrect logging when message field is removed altogether.

### ISSUE THREAD

**Issue by asatsi** [logstash-plugins/logstash-output-webhdfs#8]
If a logstash configuration splits very few fields from a log, and removes the main "message" field altogether, the plugin does not log the field that were separated. Instead it appends a string - "%{message}" to the log.

**Comment by dstore-dbap** [comment]
Hi asatsi,

sorry that it took so long for getting back to you and thanks for filing your bug report.
Will have a look at the bug and update this issue as soon as I have some news.

With kind regards and take care,
Björn

**Comment by dstore-dbap** [comment]
Hello again,

per default this plugin uses the line codec. If no format configuration is passed to this codec, it will use the default event.to_s method of logstash, which will format the string like this: "#{timestamp.to_iso8601} %{host} %{message}".

So to write events in your desired line format, be sure to configure logstash accordingly, e.g.:

```
...
output {
    webhdfs {
        host => "localhost"
        user => "test"
        path => "/user/test/test.log"
        codec => line { format => "%{type} - %{some_other_field}" }
    }
}
```

This should solve your problem.

As this is more of a configuration issue than a bug I'd like to close this issue. Please let me know if this works for you.

Take care,
Björn

**Comment by dstore-dbap** [comment]
Hello asatsi,

since I didn't hear from you in the last couple of days, I'm going to close this issue. If the solution above doesn't solve your issue, please just open a new issue. 

Thanks again for your feedback and take care,
Björn

**Comment by cherler** [comment]
solve my config issue。thanks
